# Generated by Django 4.2.23 on 2025-07-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcliente',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customcliente',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customcliente',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('emple', 'Empleado')], default='emple', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='No activo', max_length=20),
        ),
    ]
