# Generated by Django 5.2.1 on 2025-06-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.medida'),
        ),
    ]
