# Generated by Django 5.2.1 on 2025-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
