# Generated by Django 5.2.1 on 2025-05-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencompra',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resumencompra',
            name='iva',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resumencompra',
            name='total',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resumencompra',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
