# Generated by Django 5.2.1 on 2025-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
