# Generated by Django 5.2.1 on 2025-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_resumencompra_pagada_alter_resumencompra_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
