# Generated by Django 5.2 on 2025-05-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_order_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('emple', 'Empleado')], default='user', max_length=10),
        ),
    ]
