# Generated by Django 5.2.1 on 2025-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_resumencompra_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumencompra',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
